databases:
  - name: otakukaio
    databaseName: otakukaio
    user: otakukaio

services:
  - type: web
    name: otakukaio
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: otakukaio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false